package sys.model;
// Generated 05/06/2021 23:13:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbdepartamento generated by hbm2java
 */
@Entity
@Table(name="tbdepartamento"
    ,catalog="bdempleado"
)
public class Tbdepartamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private Tbpais tbpais;
     private String nombreDepartamento;
     private Set tbmunicipios = new HashSet(0);
     private Set tbempleados = new HashSet(0);

    public Tbdepartamento() {
    }

	
    public Tbdepartamento(Tbpais tbpais, String nombreDepartamento) {
        this.tbpais = tbpais;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Tbdepartamento(Tbpais tbpais, String nombreDepartamento, Set tbmunicipios, Set tbempleados) {
       this.tbpais = tbpais;
       this.nombreDepartamento = nombreDepartamento;
       this.tbmunicipios = tbmunicipios;
       this.tbempleados = tbempleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDepartamento", unique=true, nullable=false)
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPais", nullable=false)
    public Tbpais getTbpais() {
        return this.tbpais;
    }
    
    public void setTbpais(Tbpais tbpais) {
        this.tbpais = tbpais;
    }

    
    @Column(name="nombreDepartamento", nullable=false, length=50)
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbdepartamento")
    public Set getTbmunicipios() {
        return this.tbmunicipios;
    }
    
    public void setTbmunicipios(Set tbmunicipios) {
        this.tbmunicipios = tbmunicipios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbdepartamento")
    public Set getTbempleados() {
        return this.tbempleados;
    }
    
    public void setTbempleados(Set tbempleados) {
        this.tbempleados = tbempleados;
    }




}


