package sys.model;
// Generated 05/06/2021 23:13:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbempleado generated by hbm2java
 */
@Entity
@Table(name="tbempleado"
    ,catalog="bdempleado"
)
public class Tbempleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Tbdepartamento tbdepartamento;
     private Tbmunicipio tbmunicipio;
     private Tbpais tbpais;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String codigoArea;
     private String telefono;

    public Tbempleado() {
    }

    public Tbempleado(Tbdepartamento tbdepartamento, Tbmunicipio tbmunicipio, Tbpais tbpais, String nombres, String apellidos, String direccion, String codigoArea, String telefono) {
       this.tbdepartamento = tbdepartamento;
       this.tbmunicipio = tbmunicipio;
       this.tbpais = tbpais;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.codigoArea = codigoArea;
       this.telefono = telefono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEmpleado", unique=true, nullable=false)
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDepartamento", nullable=false)
    public Tbdepartamento getTbdepartamento() {
        return this.tbdepartamento;
    }
    
    public void setTbdepartamento(Tbdepartamento tbdepartamento) {
        this.tbdepartamento = tbdepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMunicipio", nullable=false)
    public Tbmunicipio getTbmunicipio() {
        return this.tbmunicipio;
    }
    
    public void setTbmunicipio(Tbmunicipio tbmunicipio) {
        this.tbmunicipio = tbmunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPais", nullable=false)
    public Tbpais getTbpais() {
        return this.tbpais;
    }
    
    public void setTbpais(Tbpais tbpais) {
        this.tbpais = tbpais;
    }

    
    @Column(name="nombres", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="codigoArea", nullable=false, length=5)
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }

    
    @Column(name="telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


