package sys.model;
// Generated 05/06/2021 23:13:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbpais generated by hbm2java
 */
@Entity
@Table(name="tbpais"
    ,catalog="bdempleado"
)
public class Tbpais  implements java.io.Serializable {


     private Integer idPais;
     private String nombrePais;
     private Set tbdepartamentos = new HashSet(0);
     private Set tbempleados = new HashSet(0);

    public Tbpais() {
    }

	
    public Tbpais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Tbpais(String nombrePais, Set tbdepartamentos, Set tbempleados) {
       this.nombrePais = nombrePais;
       this.tbdepartamentos = tbdepartamentos;
       this.tbempleados = tbempleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPais", unique=true, nullable=false)
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="nombrePais", nullable=false, length=50)
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbpais")
    public Set getTbdepartamentos() {
        return this.tbdepartamentos;
    }
    
    public void setTbdepartamentos(Set tbdepartamentos) {
        this.tbdepartamentos = tbdepartamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbpais")
    public Set getTbempleados() {
        return this.tbempleados;
    }
    
    public void setTbempleados(Set tbempleados) {
        this.tbempleados = tbempleados;
    }




}


